@extends('main')
@section('title','Games')
@section('content')
      <div class="app-template" data-reactid=".5sedzpltz4.1.2">
         <main class="wrapperMain" role="main" data-reactid=".5sedzpltz4.1.2.0">
            <div class="" data-reactid=".5sedzpltz4.1.2.0.0">
               <aside class="navSidebar" data-reactid=".5sedzpltz4.1.2.0.0.0">
                  <nav class="navProperty" data-reactid=".5sedzpltz4.1.2.0.0.0.0">
                     <h1 class="navProperty-title" data-reactid=".5sedzpltz4.1.2.0.0.0.0.0"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.0.0">Cloud Software</a></h1>
                     <div class="navProperty-toggle" data-reactid=".5sedzpltz4.1.2.0.0.0.0.2">
                        <div class="navProperty-toggleIcon iconCss-dropdown" data-reactid=".5sedzpltz4.1.2.0.0.0.0.2.0"></div>
                     </div>
                     <ul class="navProperty-list" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3">
                        <li class="navProperty-link" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Fights"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Fights.0">Tracking &amp; Analytics</a></li>
                        <li class="navProperty-link" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$People"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$People.0">Product Popularity Index</a></li>
                        <li class="navProperty-link" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Inside"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Inside.0">Audio &amp; Video Fingerprinting</a></li>
                        <li class="navProperty-link" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Shop"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Shop.0">Broadcast Monitoring</a></li>
                        <li class="navProperty-link" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Inside"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Inside.0">Copyright &amp; Distribution</a></li>
                        <li class="navProperty-link" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Shop"><a href="" class="" data-reactid=".5sedzpltz4.1.2.0.0.0.0.3.$Shop.0">Revenue Collection</a></li>
                     </ul>
                  </nav>
               </aside>
            </div>
            <div class="content content--withSidebar" data-reactid=".5sedzpltz4.1.2.0.1">
               <div class="hero hero--episodeHome " data-reactid=".5sedzpltz4.1.2.0.1.1">
                  <div class="hero-background" data-reactid=".5sedzpltz4.1.2.0.1.1.0"><img sizes="(min-width: 1180px) 950px, 100vw" src="{{ URL::asset('img/aboutpg/about1920.jpg') }}" class=" picture picture--loading" srcset="{{ URL::asset('img/aboutpg/about1920.jpg') }} 1920w, {{ URL::asset('img/aboutpg/about1280.jpg') }} 1280w, {{ URL::asset('img/aboutpg/about1024.jpg') }} 1024w" data-reactid=".5sedzpltz4.1.2.0.1.1.0.0:$heroPicture:0"></div>
                  <div class="hero-content" data-reactid=".5sedzpltz4.1.2.0.1.1.1">
                     <div class="pageTitle " data-reactid=".5sedzpltz4.1.2.0.1.1.1.0">
                        <h4 class="pageTitle-preTitle" data-reactid=".5sedzpltz4.1.2.0.1.1.1.0.0">Service Range</h4>
                        <h2 class="pageTitle-title" data-reactid=".5sedzpltz4.1.2.0.1.1.1.0.1">All Inclusive Service Range</h2>
                        <h5 class="pageTitle-subTitle" data-reactid=".5sedzpltz4.1.2.0.1.1.1.0.2">We do the heavy lifting so you can focus more on your passion.</h5>
                     </div>
                  </div>
               </div>
               <nav class="navTertiary navTertiary--twoColumns navTertiary--episodeHome" data-reactid=".5sedzpltz4.1.2.0.1.3">
                  <ul class="navTertiary-list" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$0">
                     <li class="navTertiary-link" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$0.$Golovkin-Jacobs Recap0"><a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/article/golovkin-vs-jacobs-fight-recap.html" class="" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$0.$Golovkin-Jacobs Recap0.0">Golovkin-Jacobs Recap</a></li>
                     <li class="navTertiary-link" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$0.$Gonzalez-Rungvisai Recap1"><a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/article/gonzalez-vs-rungvisai-fight-recap.html" class="" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$0.$Gonzalez-Rungvisai Recap1.0">Gonzalez-Rungvisai Recap</a></li>
                  </ul>
                  <ul class="navTertiary-list" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$1">
                     <li class="navTertiary-link" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$1.$Fight Week Coverage0"><a href="http://www.insidehboboxing.com/?tag=Gennady+Golovkin+vs.+Daniel+Jacobs" class="" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$1.$Fight Week Coverage0.0">Fight Week Coverage</a></li>
                     <li class="navTertiary-link" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$1.$Fight Week Podcasts1"><a href="https://soundcloud.com/hboboxing/sets/ggg-jacobs" class="" data-reactid=".5sedzpltz4.1.2.0.1.3.0:$1.$Fight Week Podcasts1.0">Fight Week Podcasts</a></li>
                  </ul>
               </nav>
               <div class="content-primary content-primary--episodeHome" data-reactid=".5sedzpltz4.1.2.0.1.5">
                  <div class="mediaGrid mediaGrid--twoOrFour mediaGrid--episodeHome" data-reactid=".5sedzpltz4.1.2.0.1.5.0">
                     <div class=" mediaGrid-item" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true">
                        <div class="videoItem videoItem--video" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0">
                           <div class="videoItem-content" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.0">
                              <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo.html?autoplay=true" class="videoItem-imageContainer" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.0.0">
                                 <img sizes="(min-width: 1180px) 500px, (min-width: 768px) 50vw, 100vw" title="Golovkin-Jacobs Fight Replay Promo" src="http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/golovkin-jacobs-replay-promo-100.jpg" class="videoItem-image picture picture--loading" srcset="http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/golovkin-jacobs-replay-promo-200.jpg 200w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/golovkin-jacobs-replay-promo-300.jpg 300w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/golovkin-jacobs-replay-promo-512.jpg 512w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/golovkin-jacobs-replay-promo-1024.jpg 1024w" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.0.0.0">
                                 <div class="videoItem-control videoItem-control--play" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.0.0.1"></div>
                              </a>
                           </div>
                           <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo.html?autoplay=true" class="" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.1"><span class="videoItem-title" title="Golovkin-Jacobs Fight Replay Promo" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.1.0">Golovkin-Jacobs Fight Replay Promo</span><span class="videoItem-duration" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-jacobs-fight-replay-promo=1html?autoplay=0true.0.1.2">(0:47)</span></a>
                        </div>
                     </div>
                     <div class=" mediaGrid-item" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true">
                        <div class="videoItem videoItem--video" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0">
                           <div class="videoItem-content" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.0">
                              <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview.html?autoplay=true" class="videoItem-imageContainer" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.0.0">
                                 <img sizes="(min-width: 1180px) 500px, (min-width: 768px) 50vw, 100vw" title="Hey Harold!: Golovkin vs. Jacobs Preview" src="http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-golovkin-vs-jacobs-preview-51001501_PRO35_10-100.jpg" class="videoItem-image picture picture--loading" srcset="http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-golovkin-vs-jacobs-preview-51001501_PRO35_10-200.jpg 200w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-golovkin-vs-jacobs-preview-51001501_PRO35_10-300.jpg 300w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-golovkin-vs-jacobs-preview-51001501_PRO35_10-512.jpg 512w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-golovkin-vs-jacobs-preview-51001501_PRO35_10-1024.jpg 1024w" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.0.0.0">
                                 <div class="videoItem-control videoItem-control--play" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.0.0.1"></div>
                              </a>
                           </div>
                           <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview.html?autoplay=true" class="" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.1"><span class="videoItem-title" title="Hey Harold!: Golovkin vs. Jacobs Preview" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.1.0">Hey Harold!: Golovkin vs. Jacobs Preview</span><span class="videoItem-duration" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-golovkin-vs-jacobs-preview=1html?autoplay=0true.0.1.2">(1:23)</span></a>
                        </div>
                     </div>
                     <div class=" mediaGrid-item" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true">
                        <div class="videoItem videoItem--video" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0">
                           <div class="videoItem-content" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.0">
                              <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview.html?autoplay=true" class="videoItem-imageContainer" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.0.0">
                                 <img sizes="(min-width: 1180px) 500px, (min-width: 768px) 50vw, 100vw" title="Hey Harold!: Chocolatito vs. Rungvisai Preview" src="http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-chocolatito-vs-rungvisai-preview-51005501_PRO35_10-100.jpg" class="videoItem-image picture picture--loading" srcset="http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-chocolatito-vs-rungvisai-preview-51005501_PRO35_10-200.jpg 200w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-chocolatito-vs-rungvisai-preview-51005501_PRO35_10-300.jpg 300w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-chocolatito-vs-rungvisai-preview-51005501_PRO35_10-512.jpg 512w, http://i.lv3.hbo.com/assets/images/sports/boxing/fights/2017-03-18-golovkin-vs-jacobs/video-still/hey-harold-chocolatito-vs-rungvisai-preview-51005501_PRO35_10-1024.jpg 1024w" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.0.0.0">
                                 <div class="videoItem-control videoItem-control--play" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.0.0.1"></div>
                              </a>
                           </div>
                           <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview.html?autoplay=true" class="" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.1"><span class="videoItem-title" title="Hey Harold!: Chocolatito vs. Rungvisai Preview" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.1.0">Hey Harold!: Chocolatito vs. Rungvisai Preview</span><span class="videoItem-duration" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/hey-harold-chocolatito-vs-rungvisai-preview=1html?autoplay=0true.0.1.2">(1:09)</span></a>
                        </div>
                     </div>
                     <div class=" mediaGrid-item" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true">
                        <div class="videoItem videoItem--video" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0">
                           <div class="videoItem-content" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.0">
                              <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits.html?autoplay=true" class="videoItem-imageContainer" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.0.0">
                                 <img sizes="(min-width: 1180px) 500px, (min-width: 768px) 50vw, 100vw" title="Golovkin Greatest Hits" src="http://i.lv3.hbo.com/assets/images/sports/boxing/video-stills/2013/greatest-hits-gennady-golovkin-593039-4_PRO1-100.jpg" class="videoItem-image picture picture--loading" srcset="http://i.lv3.hbo.com/assets/images/sports/boxing/video-stills/2013/greatest-hits-gennady-golovkin-593039-4_PRO1-200.jpg 200w, http://i.lv3.hbo.com/assets/images/sports/boxing/video-stills/2013/greatest-hits-gennady-golovkin-593039-4_PRO1-300.jpg 300w, http://i.lv3.hbo.com/assets/images/sports/boxing/video-stills/2013/greatest-hits-gennady-golovkin-593039-4_PRO1-512.jpg 512w, http://i.lv3.hbo.com/assets/images/sports/boxing/video-stills/2013/greatest-hits-gennady-golovkin-593039-4_PRO1-1024.jpg 1024w" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.0.0.0">
                                 <div class="videoItem-control videoItem-control--play" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.0.0.1"></div>
                              </a>
                           </div>
                           <a href="/boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits.html?autoplay=true" class="" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.1"><span class="videoItem-title" title="Golovkin Greatest Hits" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.1.0">Golovkin Greatest Hits</span><span class="videoItem-duration" data-reactid=".5sedzpltz4.1.2.0.1.5.0.0:$boxing/fights/2017/03-18-gennady-golovkin-vs-daniel-jacobs/video/golovkin-greatest-hits=1html?autoplay=0true.0.1.2">(3:59)</span></a>
                        </div>
                     </div>
                  </div>
               </div>
               -->
            </div>
         </main>
@endsection